# Generated by Django 4.2.1 on 2023-07-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClasesPartApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasespart',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
