# Generated by Django 4.2.1 on 2023-07-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClasesPartApp', '0002_clasespart_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasespart',
            name='imagen',
            field=models.ImageField(upload_to='ClasesPartApp'),
        ),
    ]
