# Generated by Django 4.2.1 on 2023-07-02 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'categoriaClase',
                'verbose_name_plural': 'categoriasClases',
            },
        ),
        migrations.CreateModel(
            name='ClaseProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='pediTuClaseApp')),
                ('precio', models.FloatField()),
                ('categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pediTuClaseApp.categoriaclase')),
            ],
            options={
                'verbose_name': 'ClaseProducto',
                'verbose_name_plural': 'ClasesProductos',
            },
        ),
    ]
