# Generated by Django 4.2.1 on 2023-07-02 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pediTuClaseApp', '0002_claseproducto_created_claseproducto_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claseproducto',
            name='created',
        ),
        migrations.RemoveField(
            model_name='claseproducto',
            name='updated',
        ),
    ]
